class RTOData {
  Map<String, String> rtoCodes = {
    // ----Andra Pradesh
    "AP01": "Adilabad / Mancherial / Nirmal",
    "AP02": "Anantapur / Hindupur",
    "AP03": "Tirupati / Chittoor / Madanapalle",
    "AP04": "Kadapa / Proddutur",
    "AP05": "Kakinada / Amalapuram / Rajahmundry",
    "AP06": "Kakinada / Amalapuram / Rajahmundry", // shared with AP05
    "AP07": "Guntur / Tenali / Piduguralla / Narasaraopet",
    "AP08": "Guntur (Distinct RTO)",
    "AP09": "Hyderabad Central (Khairatabad)",
    "AP10": "Secunderabad, Hyderabad District",
    "AP11": "Hyderabad East (Malakpet)",
    "AP12": "Hyderabad South (Bahadurpura)",
    "AP13": "Hyderabad West (Mehdipatnam)",
    "AP14": "Karimnagar (Hyderabad District)",
    "AP15": "Karimnagar / Jagtial / Peddapalli",
    "AP16":
        "Vijayawada / Gudivada / Machilipatnam / Nandigama / Nuzividu / Krishna",
    "AP17": "Vijayawada",
    "AP18": "Vijayawada",
    "AP19": "Vijayawada",
    "AP20": "Khammam / Kothagudem / Sattupalli / Yellandu",
    "AP21": "Kurnool / Adoni / Nandyal",
    "AP22": "Mahabubnagar / Pebbair / Gadwal",
    "AP23": "Sangareddy / Siddipet / Medak",
    "AP24": "Nalgonda / Bhongir / Suryapet",
    "AP25": "Nizamabad / Kamareddy",
    "AP26": "Nellore / Kavali / Gudur / Sullurpet",
    "AP27": "Ongole / Chirala / Markapur / Prakasam",
    "AP28": "Rangareddy",
    "AP29": "Rangareddy",
    "AP30": "Srikakulam",
    "AP31": "Visakhapatnam / Gajuwaka / Anakapalli",
    "AP32": "Visakhapatnam (additional RTO)",
    "AP33": "Gajuwaka (Visakhapatnam region)",
    "AP34": "Visakhapatnam (additional RTO)",
    "AP35": "Vizianagaram",
    "AP36": "Warangal / Jangaon",
    "AP37":
        "Eluru / Jangareddy Gudem / Kovvur / Tadepalli Gudem / Tanuku / Bhimavaram",
    "AP38": "Eluru (additional RTO)",
    "AP39": "Prakasam (Gudur) / Prakasam district",
    "AP40": "Uniform code introduced statewide (new series)",
    //   --Arunachal Pradesh
    "AR01": "Itanagar (Capital Complex)",
    "AR02": "Naharlagun",
    "AR03": "Tawang",
    "AR04": "Bomdila (West Kameng)",
    "AR05": "Seppa (East Kameng)",
    "AR06": "Ziro (Lower Subansiri)",
    "AR07": "Daporijo (Upper Subansiri)",
    "AR08": "Along (West Siang)",
    "AR09": "Pasighat (East Siang)",
    "AR10": "Roing (Lower Dibang Valley)",
    "AR11": "Tezu (Lohit)",
    "AR12": "Changlang",
    "AR13": "Khonsa (Tirap)",
    "AR14": "Yupia (Papum Pare)",
    "AR15": "Kurung Kumey (Koloriang)",
    "AR16": "Anini (Dibang Valley)",
    "AR17": "Tawang (alternate/new series)",
    "AR18": "Namsai",
    "AR19": "Longding",
    "AR20": "Pakke-Kessang",
    "AR21": "Lepa Rada",
    "AR22": "Shi-Yomi",
    "AR23": "Kamle",
    "AR24": "Kra Daadi",
    "AR25": "Lower Siang",
    "AR26": "Lower Dibang Valley (Roing alternate)",
    "AR27": "Lower Subansiri (Ziro alternate)",
    "AR28": "East Kameng (Seppa alternate)",
    //   ----Assam---
    "AS01": "Guwahati / Kamrup",
    "AS02": "Nagaon",
    "AS03": "Jorhat",
    "AS04": "Sivasagar",
    "AS05": "Golaghat",
    "AS06": "Dibrugarh",
    "AS07": "Lakhimpur",
    "AS08": "Dima Hasao",
    "AS09": "Karbi Anglong",
    "AS10": "Karimganj",
    "AS11": "Cachar",
    "AS12": "Sonitpur",
    "AS13": "Darrang",
    "AS14": "Nalbari",
    "AS15": "Barpeta",
    "AS16": "Kokrajhar",
    "AS17": "Dhubri",
    "AS18": "Goalpara",
    "AS19": "Bongaigaon",
    "AS20": "Assam State Transport Corporation (ASTC)",
    "AS21": "Morigaon",
    "AS22": "Dhemaji",
    "AS23": "Tinsukia",
    "AS24": "Hailakandi",
    "AS25": "Kamrup (Rural)",
    "AS26": "Chirang",
    "AS27": "Udalguri",
    "AS28": "Baksa",
    "AS29": "Majuli",
    "AS30": "Assam Police Vehicles",
    "AS31": "Hojai",
    "AS32": "Biswanath Chariali",
    "AS33": "Charaideo",
    "AS34": "South Salmara‑Mankachar",
    //   --Bihar--
    "BR01": "Patna",
    "BR02": "Gaya",
    "BR03": "Bhojpur",
    "BR04": "Chhapra (Saran)",
    "BR05": "Motihari (East Champaran)",
    "BR06": "Muzaffarpur",
    "BR07": "Darbhanga",
    "BR08": "Munger",
    "BR09": "Begusarai",
    "BR10": "Bhagalpur",
    "BR11": "Purnea",
    "BR19": "Saharsa",
    "BR21": "Nalanda (Bihar Sharif)",
    "BR22": "Bettiah (West Champaran)",
    "BR24": "Dehri (Rohtas)",
    "BR25": "Jehanabad",
    "BR26": "Aurangabad",
    "BR27": "Nawada",
    "BR28": "Gopalganj",
    "BR29": "Siwan",
    "BR30": "Sitamarhi",
    "BR31": "Vaishali (Hajipur)",
    "BR32": "Madhubani",
    "BR33": "Samastipur",
    "BR34": "Khagaria",
    "BR37": "Kishanganj",
    "BR38": "Araria",
    "BR39": "Katihar",
    "BR43": "Madhepura",
    "BR44": "Buxar",
    "BR45": "Bhabua (Kaimur)",
    "BR46": "Jamui",
    "BR50": "Supaul",
    "BR51": "Banka",
    "BR52": "Sheikhpura",
    "BR53": "Lakhisarai",
    "BR55": "Sheohar",
    "BR56": "Arwal",
    "BR57": "Rohtas (Sasaram)",
    //   --Chhattisgarh--
    "CG01": "Governor of Chhattisgarh (State Level RTO)",
    "CG02": "Government of Chhattisgarh (State Government Vehicles)",
    "CG03": "Chhattisgarh Police Vehicles",
    "CG04": "Raipur (Raipur district)",
    "CG05": "Dhamtari (Dhamtari district)",
    "CG06": "Mahasamund (Mahasamund district)",
    "CG07": "Durg",
    "CG08": "Rajnandgaon",
    "CG09": "Kawardha (Kabirdham)",
    "CG10": "Bilaspur",
    "CG11": "Janjgir‑Champa",
    "CG12": "Korba",
    "CG13": "Raigarh",
    "CG14": "Jashpur Nagar",
    "CG15": "Ambikapur",
    "CG16": "Baikunthpur (Koriya)",
    "CG17": "Jagdalpur (Bastar)",
    "CG18": "Dantewada",
    "CG19": "Kanker",
    "CG20": "Bijapur",
    "CG21": "Narayanpur",
    "CG22": "Baloda Bazar",
    "CG23": "Gariaband",
    "CG24": "Balod",
    "CG25": "Bemetara",
    "CG26": "Sukma",
    "CG27": "Kondagaon",
    "CG28": "Mungeli",
    "CG29": "Surajpur",
    "CG30": "Balrampur",
    "CG99": "State Transport Authority",
    //   --Chandigarh--
    "CH01": "Chandigarh RLA (Registering and Licensing Authority)",
    "CH02": "Chandigarh RTO – Commercial Vehicles",
    "CH03": "Chandigarh RTO – Private Vehicles",
    "CH04": "Chandigarh RTO – Government Vehicles",
    "CH23": "Chandigarh RTO – Additional / Reserved",
    //   -- Dadra and Nagar Haveli abd Daman and Diu ---
    "DD01":
        "Dadra & Nagar Haveli (Silvassa RTO)", // DD‑01: Silvassa (Dadra & Nagar Haveli) :contentReference[oaicite:0]{index=0}
    "DD02": "Diu RTO", // DD‑02: Diu RTO :contentReference[oaicite:1]{index=1}
    "DD03":
        "Daman RTO", // DD‑03: Daman RTO :contentReference[oaicite:2]{index=2}
    //   --Delhi--
    "DL01": "Mall Road, North Delhi",
    "DL02": "IP Depot, North Delhi",
    "DL03": "Sheikh Sarai, South Delhi",
    "DL04": "Janakpuri, West Delhi",
    "DL05": "Loni Road, North East Delhi",
    "DL06": "Sarai Kale Khan, Central Delhi",
    "DL07": "Mayur Vihar, East Delhi",
    "DL08": "Wazirpur, North West Delhi",
    "DL09": "Janakpuri, South West Delhi",
    "DL10": "West Delhi (Rajouri Garden)",
    "DL11": "Rohini, North West Delhi",
    "DL12": "Vasant Vihar, South West Delhi",
    "DL13": "Surajmal Vihar, East Delhi",
    "DL14": "Sonipat (for vehicles registered before Haryana separation)",
    "DL15": "Gurgaon (historic, no longer used)",
    "DL16": "Ashok Vihar, North West Delhi (Commercial Vehicles)",
    "DL17": "IP Depot (Commercial Vehicles)",
    "DL18": "Saket, South Delhi",
    "DL20": "DTC Headquarters (for Delhi Transport Corporation buses)",
    //   --Goa--
    "GA01": "Panaji (North Goa)",
    "GA02": "Margao (South Goa)",
    "GA03": "Mapusa (North Goa)",
    "GA04": "Ponda (North Goa)",
    "GA05": "Bicholim (North Goa)",
    "GA06": "Vasco da Gama (South Goa)",
    "GA07": "Canacona (South Goa)",
    "GA08": "Quepem (South Goa)",
    "GA09": "Pernem (North Goa)",
    "GA10": "Sanguem (South Goa)",
    "GA11": "Dharbandora (South Goa)",
    //   --Gujarat--
    "GJ01": "Ahmedabad (East)",
    "GJ02": "Mehsana",
    "GJ03": "Rajkot",
    "GJ04": "Bhavnagar",
    "GJ05": "Surat",
    "GJ06": "Vadodara",
    "GJ07": "Nadiad",
    "GJ08": "Palanpur",
    "GJ09": "Himatnagar",
    "GJ10": "Jamnagar",
    "GJ11": "Junagadh",
    "GJ12": "Kutch-Bhuj",
    "GJ13": "Surendranagar",
    "GJ14": "Amreli",
    "GJ15": "Valsad",
    "GJ16": "Bharuch",
    "GJ17": "Godhra",
    "GJ18": "Gandhinagar",
    "GJ19": "Bardoli",
    "GJ20": "Dahod",
    "GJ21": "Navsari",
    "GJ22": "Anand",
    "GJ23": "Patan",
    "GJ24": "Porbandar",
    "GJ25": "Rajpipla",
    "GJ26": "Ahmedabad (West)",
    "GJ27": "Veraval",
    "GJ28": "Arvalli (Modasa)",
    "GJ29": "Chhota Udaipur",
    "GJ30": "Botad",
    "GJ31": "Morbi",
    "GJ32": "Gir Somnath",
    "GJ33": "Mahisagar (Lunawada)",
    "GJ34": "Devbhoomi Dwarka",
    //   --Himachal Pradesh--
    "HP01": "Reckong Peo (Kinnaur)",
    "HP02": "Shimla (Urban)",
    "HP03": "Shimla (Rural)",
    "HP04": "Rampur (Shimla)",
    "HP05": "Theog (Shimla)",
    "HP06": "Suni (Shimla)",
    "HP07": "Chopal (Shimla)",
    "HP08": "Rohru (Shimla)",
    "HP09": "Solan",
    "HP10": "Arki (Solan)",
    "HP11": "Nalagarh (Solan)",
    "HP12": "Kandaghat (Solan)",
    "HP13": "Parwanoo (Solan)",
    "HP14": "Dharamshala (Kangra)",
    "HP15": "Palampur (Kangra)",
    "HP16": "Dehra (Kangra)",
    "HP17": "Nurpur (Kangra)",
    "HP18": "Baijnath (Kangra)",
    "HP19": "Nagrota Bagwan (Kangra)",
    "HP20": "Hamirpur",
    "HP21": "Nadaun (Hamirpur)",
    "HP22": "Barsar (Hamirpur)",
    "HP23": "Mandi",
    "HP24": "Sundernagar (Mandi)",
    "HP25": "Jogindernagar (Mandi)",
    "HP26": "Karsog (Mandi)",
    "HP27": "Padhar (Mandi)",
    "HP28": "Chachyot (Mandi)",
    "HP29": "Kullu",
    "HP30": "Manali (Kullu)",
    "HP31": "Banjar (Kullu)",
    "HP32": "Bilaspur",
    "HP33": "Ghumarwin (Bilaspur)",
    "HP34": "Swarghat (Bilaspur)",
    "HP35": "Chamba",
    "HP36": "Dalhousie (Chamba)",
    "HP37": "Bharmaur (Chamba)",
    "HP38": "Tissa (Chamba)",
    "HP39": "Una",
    "HP40": "Amb (Una)",
    "HP41": "Gagret (Una)",
    "HP42": "Nahan (Sirmaur)",
    "HP43": "Paonta Sahib (Sirmaur)",
    "HP44": "Rajgarh (Sirmaur)",
    "HP45": "Shillai (Sirmaur)",
    "HP46": "Solan (Additional)",
    "HP47": "Bilaspur (Additional)",
    "HP48": "Mandi (Additional)",
    "HP49": "Hamirpur (Additional)",
    "HP50": "Kullu (Additional)",
    "HP51": "Una (Additional)",
    "HP52": "Chamba (Additional)",
    "HP53": "Sirmaur (Additional)",
    "HP54": "Kangra (Additional)",
    "HP55": "Lahaul-Spiti (Keylong)",
    "HP56": "Tandi (Lahaul-Spiti)",
    //   --Haryana--
    "HR01": "Ambala",
    "HR02": "Barara (Ambala)",
    "HR03": "Naraingarh (Ambala)",
    "HR04": "Panchkula",
    "HR05": "Kalka (Panchkula)",
    "HR06": "Panipat",
    "HR07": "Assandh (Karnal)",
    "HR08": "Karnal",
    "HR09": "Gharaunda (Karnal)",
    "HR10": "Kaithal",
    "HR11": "Guhla (Kaithal)",
    "HR12": "Kurukshetra",
    "HR13": "Pehowa (Kurukshetra)",
    "HR14": "Yamunanagar",
    "HR15": "Jagadhri (Yamunanagar)",
    "HR16": "Faridabad",
    "HR17": "Ballabgarh (Faridabad)",
    "HR18": "Palwal",
    "HR19": "Gurgaon (South)",
    "HR20": "Gurgaon (North)",
    "HR21": "Dharuhera (Rewari)",
    "HR22": "Rewari",
    "HR23": "Narnaul",
    "HR24": "Mahendragarh",
    "HR25": "Bhiwani",
    "HR26": "Rohtak",
    "HR27": "Bahadurgarh (Jhajjar)",
    "HR28": "Gohana (Sonipat)",
    "HR29": "Jhajjar",
    "HR30": "Meham (Rohtak)",
    "HR31": "Charkhi Dadri",
    "HR32": "Sonipat",
    "HR33": "Ganaur (Sonipat)",
    "HR34": "Jind",
    "HR35": "Narwana (Jind)",
    "HR36": "Safidon (Jind)",
    "HR37": "Hansi (Hisar)",
    "HR38": "Hisar",
    "HR39": "Fatehabad",
    "HR40": "Tohana (Fatehabad)",
    "HR41": "Sirsa",
    "HR42": "Dabwali (Sirsa)",
    "HR43": "Ratia (Fatehabad)",
    "HR44": "Ellenabad (Sirsa)",
    "HR45": "Beri (Jhajjar)",
    "HR46": "Kosli (Rewari)",
    "HR47": "Pataudi (Gurgaon)",
    "HR48": "Bawal (Rewari)",
    "HR49": "Kalayat (Kaithal)",
    "HR50": "Barwala (Hisar)",
    "HR51": "Khanpur Kalan (Sonipat)",
    "HR52": "Nuh (Mewat)",
    "HR53": "Ferozepur Jhirka (Nuh)",
    "HR54": "Punhana (Nuh)",
    "HR55": "Hodal (Palwal)",
    "HR56": "Hathin (Palwal)",
    "HR57": "Indri (Karnal)",
    "HR58": "Radaur (Yamunanagar)",
    "HR59": "Shahabad (Kurukshetra)",
    "HR60": "Beri (Jhajjar)",
    "HR61": "Samalkha (Panipat)",
    //   --Jharkhand--
    "JH01": "Ranchi",
    "JH02": "Hazaribagh",
    "JH03": "Daltonganj (Palamu)",
    "JH04": "Dumka",
    "JH05": "Jamshedpur (East Singhbhum)",
    "JH06": "Chaibasa (West Singhbhum)",
    "JH07": "Gumla",
    "JH08": "Lohardaga",
    "JH09": "Bokaro",
    "JH10": "Deoghar",
    "JH11": "Giridih",
    "JH12": "Koderma",
    "JH13": "Chatra",
    "JH14": "Garhwa",
    "JH15": "Pakur",
    "JH16": "Sahebganj",
    "JH17": "Latehar",
    "JH18": "Simdega",
    "JH19": "Jamtara",
    "JH20": "Saraikela-Kharsawan",
    "JH21": "Ramgarh",
    "JH22": "Khunti",
    //   --Jammu and kashmir--
    "JK01": "Srinagar",
    "JK02": "Jammu",
    "JK03": "Anantnag",
    "JK04": "Budgam",
    "JK05": "Baramulla",
    "JK06": "Doda",
    "JK07": "Kargil",
    "JK08": "Kathua",
    "JK09": "Kupwara",
    "JK10": "Leh",
    "JK11": "Rajouri",
    "JK12": "Poonch",
    "JK13": "Pulwama",
    "JK14": "Udhampur",
    "JK15": "Bandipora",
    "JK16": "Ganderbal",
    "JK17": "Kulgam",
    "JK18": "Shopian",
    //   --Karnataka--
    "KA01": "Bengaluru Central (Koramangala)",
    "KA02": "Bengaluru West (Rajajinagar)",
    "KA03": "Bengaluru East (Indiranagar)",
    "KA04": "Bengaluru North (Yeshwanthpur)",
    "KA05": "Bengaluru South (Jayanagar)",
    "KA06": "Tumakuru",
    "KA07": "Kolar",
    "KA08": "Kolar Gold Fields",
    "KA09": "Mysuru West",
    "KA10": "Chamarajanagar",
    "KA11": "Mandya",
    "KA12": "Madikeri (Kodagu)",
    "KA13": "Hassan",
    "KA14": "Shimoga",
    "KA15": "Chitradurga",
    "KA16": "Davanagere",
    "KA17": "Krishnarajapuram",
    "KA18": "Ramanagara",
    "KA19": "Mangaluru",
    "KA20": "Udupi",
    "KA21": "Puttur",
    "KA22": "Belagavi",
    "KA23": "Chikkodi",
    "KA24": "Bailhongal",
    "KA25": "Dharwad",
    "KA26": "Gadag",
    "KA27": "Haveri",
    "KA28": "Bijapur",
    "KA29": "Bagalkot",
    "KA30": "Karwar (Uttara Kannada)",
    "KA31": "Sirsi",
    "KA32": "Gulbarga",
    "KA33": "Bellary",
    "KA34": "Hospet",
    "KA35": "Raichur",
    "KA36": "Koppal",
    "KA37": "Yadgir",
    "KA38": "Chikkamagaluru",
    "KA39": "Hunsur",
    "KA40": "Bengaluru Rural",
    "KA41": "Bengaluru Electronic City",
    "KA42": "RTO Devanahalli",
    "KA43": "Tiptur",
    "KA44": "Kundapura",
    "KA45": "Sakaleshpur",
    "KA46": "Yelahanka (Bengaluru North-East)",
    "KA47": "Nagamangala",
    "KA48": "Shivamogga",
    "KA49": "Jamkhandi",
    "KA50": "Channarayapatna",
    "KA51": "K.R. Puram",
    "KA52": "Basavakalyan",
    "KA53": "Shantinagar (Bengaluru South-East)",
    "KA54": "Nelamangala",
    "KA55": "Chamrajpet (Bengaluru South)",
    "KA56": "Dandeli",
    "KA57": "Gokak",
    "KA58": "Bhalki",
    "KA59": "Basavakalyan",
    "KA60": "Bantwal",
    "KA61": "Vijayanagar (Bengaluru)",
    "KA62": "Shivajinagar (Bengaluru)",
    "KA63": "Kudligi",
    "KA64": "Sankeshwar",
    "KA65": "Indi",
    "KA66": "Turuvekere",
    "KA67": "Sandur",
    "KA68": "Sullia",
    "KA69": "Tikota",
    //   --Kerala--
    "KL01": "Thiruvananthapuram",
    "KL02": "Kollam",
    "KL03": "Pathanamthitta",
    "KL04": "Alappuzha",
    "KL05": "Kottayam",
    "KL06": "Idukki",
    "KL07": "Ernakulam",
    "KL08": "Thrissur",
    "KL09": "Palakkad",
    "KL10": "Malappuram",
    "KL11": "Kozhikode",
    "KL12": "Wayanad",
    "KL13": "Kannur",
    "KL14": "Kasaragod",
    "KL15": "Thiruvananthapuram (Sub-RTO)",
    "KL16": "Attingal",
    "KL17": "Neyyattinkara",
    "KL18": "Nedumangad",
    "KL19": "Parassala",
    "KL20": "Varkala",
    "KL21": "Kunnathur",
    "KL22": "Karunagappally",
    "KL23": "Kottarakkara",
    "KL24": "Punalur",
    "KL25": "Adoor",
    "KL26": "Thiruvalla",
    "KL27": "Mallappally",
    "KL28": "Ranni",
    "KL29": "Chengannur",
    "KL30": "Mavelikkara",
    "KL31": "Kayamkulam",
    "KL32": "Cherthala",
    "KL33": "Changanassery",
    "KL34": "Pala",
    "KL35": "Vaikom",
    "KL36": "Ettumanoor",
    "KL37": "Thodupuzha",
    "KL38": "Peerumedu",
    "KL39": "Muvattupuzha",
    "KL40": "Perumbavoor",
    "KL41": "Aluva",
    "KL42": "North Paravur",
    "KL43": "Mattancherry",
    "KL44": "Kothamangalam",
    "KL45": "Thripunithura",
    "KL46": "Angamaly",
    "KL47": "Chalakudy",
    "KL48": "Kodungallur",
    "KL49": "Wadakkanchery",
    "KL50": "Guruvayur",
    "KL51": "Pattambi",
    "KL52": "Ottappalam",
    "KL53": "Mannarkkad",
    "KL54": "Alathur",
    "KL55": "Perinthalmanna",
    "KL56": "Ponnani",
    "KL57": "Tirur",
    "KL58": "Koyilandy",
    "KL59": "Vadakara",
    "KL60": "Thalassery",
    "KL61": "Thaliparamba",
    "KL62": "Kanjangad",
    "KL63": "Uzhavoor",
    "KL64": "Kondotty",
    "KL65": "Kuttanad",
    //   Ladakh
    "LA01": "Leh",
    "LA02": "Kargil",
    //   Lakshadweep
    "LD01": "Kavaratti",
    //   Maharashtra
    "MH01": "Mumbai (South)",
    "MH02": "Mumbai (West)",
    "MH03": "Mumbai (East)",
    "MH04": "Thane",
    "MH05": "Kalyan",
    "MH06": "Pen",
    "MH07": "Sindhudurg",
    "MH08": "Ratnagiri",
    "MH09": "Kolhapur",
    "MH10": "Sangli",
    "MH11": "Satara",
    "MH12": "Pune",
    "MH13": "Solapur",
    "MH14": "Pimpri-Chinchwad",
    "MH15": "Nashik",
    "MH16": "Ahmednagar",
    "MH17": "Shrirampur",
    "MH18": "Dhule",
    "MH19": "Jalgaon",
    "MH20": "Aurangabad",
    "MH21": "Jalna",
    "MH22": "Parbhani",
    "MH23": "Beed",
    "MH24": "Osmanabad",
    "MH25": "Latur",
    "MH26": "Amravati",
    "MH27": "Akola",
    "MH28": "Buldhana",
    "MH29": "Yavatmal",
    "MH30": "Nagpur (City)",
    "MH31": "Nagpur (Rural)",
    "MH32": "Wardha",
    "MH33": "Gadchiroli",
    "MH34": "Chandrapur",
    "MH35": "Gondia",
    "MH36": "Bhandara",
    "MH37": "Washim",
    "MH38": "Hingoli",
    "MH39": "Nandurbar",
    "MH40": "Wadi (Nagpur)",
    "MH41": "Akluj",
    "MH42": "Vasai-Virar",
    "MH43": "Navi Mumbai",
    "MH44": "Ambejogai",
    "MH45": "Panvel",
    "MH46": "Borivali",
    "MH47": "Andheri",
    "MH48": "Vikhroli",
    "MH49": "Dahisar",
    "MH50": "Kurla",
    "MH51": "Chembur",
    "MH52": "Goregaon",
    "MH53": "Kandivali",
    "MH54": "Mulund",
    "MH55": "Ghatkopar",
    "MH56": "Dindoshi",
    "MH57": "Worli",
    "MH58": "Malad",
    "MH59": "Bandra",
    "MH60": "Tardeo",
    //   Meghalaya
    "ML01": "Shillong",
    "ML02": "Jowai",
    "ML03": "Tura",
    "ML04": "Williamnagar",
    "ML05": "Baghmara",
    "ML06": "Nongpoh",
    "ML07": "Mawkyrwat",
    "ML08": "Khliehriat",
    "ML09": "Ampati",
    "ML10": "Resubelpara",
    //   Manipur
    "MN01": "Imphal West",
    "MN02": "Churachandpur",
    "MN03": "Kangpokpi",
    "MN04": "Thoubal",
    "MN05": "Bishnupur",
    "MN06": "Ukhrul",
    "MN07": "Imphal East",
    "MN08": "Senapati",
    "MN09": "Tamenglong",
    "MN10": "Chandel",
    "MN11": "Jiribam",
    "MN12": "Pherzawl",
    "MN13": "Noney",
    "MN14": "Kakching",
    "MN15": "Kamjong",
    "MN16": "Tengnoupal",
    //   Madhya Pradesh
    "MP01": "State Governor's Vehicle",
    "MP02": "State Government",
    "MP03": "Indore",
    "MP04": "Bhopal",
    "MP05": "Gwalior",
    "MP06": "Jabalpur",
    "MP07": "Rewa",
    "MP08": "Shahdol",
    "MP09": "Ujjain",
    "MP10": "Sagar",
    "MP11": "Chhatarpur",
    "MP12": "Tikamgarh",
    "MP13": "Satna",
    "MP14": "Sehore",
    "MP15": "Raisen",
    "MP16": "Rajgarh",
    "MP17": "Vidisha",
    "MP18": "Damoh",
    "MP19": "Panna",
    "MP20": "Katni",
    "MP21": "Jhabua",
    "MP22": "Khargone (West Nimar)",
    "MP23": "Khandwa (East Nimar)",
    "MP24": "Barwani",
    "MP25": "Harda",
    "MP26": "Betul",
    "MP27": "Hoshangabad",
    "MP28": "Dewas",
    "MP29": "Dhar",
    "MP30": "Shajapur",
    "MP31": "Ratlam",
    "MP32": "Mandsaur",
    "MP33": "Neemuch",
    "MP34": "Morena",
    "MP35": "Bhind",
    "MP36": "Sheopur",
    "MP37": "Datia",
    "MP38": "Ashoknagar",
    "MP39": "Seoni",
    "MP40": "Balaghat",
    "MP41": "Mandla",
    "MP42": "Dindori",
    "MP43": "Sidhi",
    "MP44": "Singrauli",
    "MP45": "Umaria",
    "MP46": "Anuppur",
    "MP47": "Alirajpur",
    "MP48": "Burhanpur",
    "MP49": "Agar Malwa",
    "MP50": "Niwari",
    //   Mizoram
    "MZ01": "Aizawl",
    "MZ02": "Lunglei",
    "MZ03": "Saiha",
    "MZ04": "Champhai",
    "MZ05": "Kolasib",
    "MZ06": "Serchhip",
    "MZ07": "Lawngtlai",
    "MZ08": "Mamit",
    "MZ09": "Saitual",
    "MZ10": "Hnahthial",
    "MZ11": "Khawzawl",
    //   Nagaland
    "NL01": "Kohima",
    "NL02": "Mokokchung",
    "NL03": "Tuensang",
    "NL04": "Mon",
    "NL05": "Wokha",
    "NL06": "Zunheboto",
    "NL07": "Dimapur",
    "NL08": "Phek",
    "NL09": "Peren",
    "NL10": "Longleng",
    "NL11": "Kiphire",
    "NL12": "Noklak",
    //   Odisha
    "OD01": "Balasore",
    "OD02": "Bhadrak",
    "OD03": "Bhubaneswar",
    "OD04": "Cuttack",
    "OD05": "Dhenkanal",
    "OD06": "Ganjam, Berhampur",
    "OD07": "Kalahandi",
    "OD08": "Keonjhar",
    "OD09": "Koraput",
    "OD10": "Mayurbhanj",
    "OD11": "Phulbani",
    "OD12": "Puri",
    "OD13": "Rourkela",
    "OD14": "Sambalpur",
    "OD15": "Sundergarh",
    "OD16": "Baragarh",
    "OD17": "Rayagada",
    "OD18": "Angul",
    "OD19": "Jagatsinghpur",
    "OD20": "Bhawanipatna",
    "OD21": "Gajapati",
    "OD22": "Jharsuguda",
    "OD23": "Nabarangpur",
    "OD24": "Nayagarh",
    "OD25": "Nuapada",
    "OD26": "Boudh",
    "OD27": "Debagarh",
    "OD28": "Kendrapara",
    "OD29": "Malkangiri",
    "OD30": "Sonepur",
    "OD31": "Bhanjanagar",
    "OD32": "Bolangir",
    "OD33": "Chhatrapur",
    "OD34": "Jajpur",
    "OD35": "Talcher",
    "OD99": "STA Odisha (State Transport Authority)",
    //   Punjab
    "PB01": "Chandigarh",
    "PB02": "Amritsar",
    "PB03": "Bathinda",
    "PB04": "Faridkot",
    "PB05": "Ferozepur",
    "PB06": "Gurdaspur",
    "PB07": "Hoshiarpur",
    "PB08": "Jalandhar",
    "PB09": "Kapurthala",
    "PB10": "Ludhiana",
    "PB11": "Patiala",
    "PB12": "Ropar",
    "PB13": "Sangrur",
    "PB14": "Ajnala",
    "PB15": "Abohar",
    "PB16": "Anandpur Sahib",
    "PB17": "Baba Bakala",
    "PB18": "Batala",
    "PB19": "Barnala",
    "PB20": "Balachaur",
    "PB21": "Dasuya",
    "PB22": "Fazilka",
    "PB23": "Fatehgarh Sahib",
    "PB24": "Fazilka",
    "PB25": "Jagraon",
    "PB26": "Khanna",
    "PB27": "Kharar",
    "PB28": "Malerkotla",
    "PB29": "Moga",
    "PB30": "Muktsar",
    "PB31": "Nawanshahr",
    "PB32": "Nakodar",
    "PB33": "Nabha",
    "PB34": "Pathankot",
    "PB35": "Phagwara",
    "PB36": "Phillaur",
    "PB37": "Rajpura",
    "PB38": "Rampura Phul",
    "PB39": "Samana",
    "PB40": "Samrala",
    "PB41": "Sunam",
    "PB42": "Tarn Taran",
    "PB43": "Zira",
    "PB44": "Amloh",
    "PB45": "Khamano",
    "PB46": "Budhlada",
    "PB47": "Jaitu",
    "PB48": "Khadoor Sahib",
    "PB49": "Mohali",
    "PB50": "Patti",
    "PB51": "Raikot",
    "PB52": "Nihal Singh Wala",
    "PB53": "Dera Bassi",
    "PB54": "Dhuri",
    "PB55": "Gidderbaha",
    "PB56": "Jalalabad",
    "PB57": "Malout",
    "PB58": "Mukerian",
    "PB59": "Payal",
    "PB60": "Raikot",
    "PB81": "STA Punjab (State Transport Authority)",
    // Puducherry
    "PY01": "Puducherry",
    "PY02": "Karaikal",
    "PY03": "Mahe",
    "PY04": "Yanam",
    "PY05": "Oulgaret (Puducherry Urban)",
    //  Rajasthan
    "RJ01": "Ajmer",
    "RJ02": "Alwar",
    "RJ03": "Banswara",
    "RJ04": "Barmer",
    "RJ05": "Bharatpur",
    "RJ06": "Bhilwara",
    "RJ07": "Bikaner",
    "RJ08": "Bundi",
    "RJ09": "Chittorgarh",
    "RJ10": "Churu",
    "RJ11": "Dholpur",
    "RJ12": "Dungarpur",
    "RJ13": "Sri Ganganagar",
    "RJ14": "Jaipur",
    "RJ15": "Jaisalmer",
    "RJ16": "Jalore",
    "RJ17": "Jhalawar",
    "RJ18": "Jhunjhunu",
    "RJ19": "Jodhpur",
    "RJ20": "Kota",
    "RJ21": "Nagaur",
    "RJ22": "Pali",
    "RJ23": "Sikar",
    "RJ24": "Sirohi",
    "RJ25": "Sawai Madhopur",
    "RJ26": "Tonk",
    "RJ27": "Udaipur",
    "RJ28": "Baran",
    "RJ29": "Dausa",
    "RJ30": "Rajsamand",
    "RJ31": "Hanumangarh",
    "RJ32": "Kotputli",
    "RJ33": "Ramganj Mandi",
    "RJ34": "Karauli",
    "RJ35": "Pratapgarh",
    "RJ36": "Beawar",
    "RJ37": "Didwana",
    "RJ38": "Kekri",
    "RJ39": "Bhiwadi",
    "RJ40": "Shahpura",
    //Sikkim
    "SK01": "Gangtok",
    "SK02": "Gyalshing (West Sikkim)",
    "SK03": "Mangan (North Sikkim)",
    "SK04": "Namchi (South Sikkim)",
    //   Telangana
    "TS01": "Adilabad",
    "TS02": "Karimnagar",
    "TS03": "Warangal",
    "TS04": "Khammam",
    "TS05": "Nalgonda",
    "TS06": "Mahbubnagar",
    "TS07": "Ranga Reddy",
    "TS08": "Medchal–Malkajgiri",
    "TS09": "Hyderabad Central",
    "TS10": "Hyderabad North",
    "TS11": "Hyderabad East",
    "TS12": "Hyderabad South",
    "TS13": "Hyderabad West",
    "TS14": "Reserved",
    "TS15": "Siddipet",
    "TS16": "Nizamabad",
    "TS17": "Kamareddy",
    "TS18": "Jagitial",
    "TS19": "Peddapalli",
    "TS20": "Mancherial",
    "TS21": "Nirmal",
    "TS22": "Asifabad (Kumuram Bheem)",
    "TS23": "Warangal (Urban)",
    "TS24": "Warangal (Rural)",
    "TS25": "Jayashankar Bhupalapally",
    "TS26": "Mahabubabad",
    "TS27": "Jangaon",
    "TS28": "Suryapet",
    "TS29": "Yadadri Bhuvanagiri",
    "TS30": "Nagarkurnool",
    "TS31": "Wanaparthy",
    "TS32": "Jogulamba Gadwal",
    "TS33": "Vikarabad",
    "TS34": "Medak",
    "TS35": "Sangareddy",
    "TS36": "Narayanpet",
    "TS37": "Mulugu",
    "TS38": "Narayanpet",
    "TS39": "Reserved / New Districts",
    "TS40": "Bhadradri Kothagudem",
    //Tamil Nadu
    "TN01": "Chennai (Central) – Ayanavaram",
    "TN02": "Chennai (North West) – Anna Nagar",
    "TN03": "Chennai (North East) – Tondiarpet",
    "TN04": "Chennai (East) – Basin Bridge",
    "TN05": "Chennai (North) – Kolathur",
    "TN06": "Chennai (South East) – Mandaveli",
    "TN07": "Chennai (South West) – KK Nagar",
    "TN09": "Chennai (West) – K.K. Nagar",
    "TN10": "Chennai (South) – Thiruvanmiyur",
    "TN11": "Tambaram",
    "TN12": "Poonamallee",
    "TN13": "Ambattur",
    "TN14": "Sholinganallur",
    "TN15": "Ulundurpet",
    "TN16": "Tindivanam",
    "TN18": "Red Hills",
    "TN19": "Chengalpattu",
    "TN20": "Thiruvallur",
    "TN21": "Kanchipuram",
    "TN22": "Meenambakkam",
    "TN23": "Vellore",
    "TN24": "Krishnagiri",
    "TN25": "Thiruvannamalai",
    "TN26": "Dharmapuri",
    "TN27": "Salem (West)",
    "TN28": "Namakkal (North)",
    "TN29": "Dharmapuri",
    "TN30": "Salem (East)",
    "TN31": "Cuddalore",
    "TN32": "Villupuram",
    "TN33": "Erode (East)",
    "TN34": "Gobichettipalayam",
    "TN36": "Coimbatore (North)",
    "TN37": "Coimbatore (South)",
    "TN38": "Pollachi",
    "TN39": "Tiruppur (North)",
    "TN40": "Tiruppur (South)",
    "TN41": "Mettupalayam",
    "TN43": "Ooty (The Nilgiris)",
    "TN45": "Tiruchirapalli (West)",
    "TN46": "Perambalur",
    "TN47": "Karur",
    "TN48": "Srirangam",
    "TN49": "Thanjavur",
    "TN50": "Tiruvarur",
    "TN51": "Nagapattinam",
    "TN52": "Sivaganga",
    "TN54": "Madurai (South)",
    "TN55": "Madurai (North)",
    "TN56": "Dindigul",
    "TN57": "Palani",
    "TN58": "Theni",
    "TN59": "Madurai (Central)",
    "TN60": "Virudhunagar",
    "TN61": "Kumbakonam",
    "TN63": "Ramanathapuram",
    "TN64": "Sivakasi",
    "TN65": "Tuticorin (Thoothukudi)",
    "TN66": "Tirunelveli",
    "TN67": "Nagercoil",
    "TN68": "Marthandam",
    "TN69": "Tenkasi",
    "TN70": "Hosur",
    "TN72": "Ranipet",
    "TN73": "Ariyalur",
    "TN74": "Srivilliputhur",
    "TN75": "Dharapuram",
    "TN76": "Tiruchendur",
    "TN77": "Attur",
    "TN78": "Tiruvannamalai (South)",
    "TN79": "Tindivanam",
    "TN81": "Vaniyambadi",
    "TN83": "Sankagiri",
    "TN84": "Gudalur (Nilgiris)",
    "TN85": "Mayiladuthurai",
    "TN86": "Aranthangi",
    "TN87": "Udumalpet",
    "TN88": "Karaikudi",
    "TN89": "Perundurai",
    "TN90": "Ambasamudram",
    "TN91": "Sathyamangalam",
    "TN92": "Mettur",
    "TN93": "Tirupathur",
    "TN94": "Pattukkottai",
    "TN95": "Coimbatore (Central)",
    "TN96": "Sivagangai",
    "TN97": "Arani",
    "TN98": "Manamadurai",
    "TN99": "Namakkal (South)",
    //Tripura
    "TR01": "Agartala",
    "TR02": "Udaipur",
    "TR03": "Kailashahar",
    "TR04": "Dharmanagar",
    //Uttarakhand
    "UK01": "Almora",
    "UK02": "Bageshwar",
    "UK03": "Champawat",
    "UK04": "Nainital",
    "UK05": "Pithoragarh",
    "UK06": "Udham Singh Nagar",
    "UK07": "Dehradun",
    "UK08": "Haridwar",
    "UK09": "Pauri",
    "UK10": "Tehri",
    "UK11": "Chamoli",
    "UK12": "Rudraprayag",
    "UK13": "Uttarkashi",
    //Uttar Pradesh
    "UP01": "Saharanpur",
    "UP02": "Muzaffarnagar",
    "UP03": "Bulandshahr",
    "UP04": "Ghaziabad",
    "UP05": "Meerut",
    "UP06": "Gautam Buddha Nagar (Noida)",
    "UP07": "Baghpat",
    "UP08": "Shamli",
    "UP09": "Rampur",
    "UP10": "Moradabad",
    "UP11": "Bijnor",
    "UP12": "Amroha (Jyotiba Phule Nagar)",
    "UP13": "Sambhal",
    "UP14": "Badayun",
    "UP15": "Bareilly",
    "UP16": "Pilibhit",
    "UP17": "Shahjahanpur",
    "UP18": "Aligarh",
    "UP19": "Etah",
    "UP20": "Kanshiram Nagar (Kasganj)",
    "UP21": "Mainpuri",
    "UP22": "Agra",
    "UP23": "Firozabad",
    "UP24": "Mathura",
    "UP25": "Hathras",
    "UP26": "Etawah",
    "UP27": "Auraiya",
    "UP28": "Kanpur Dehat",
    "UP29": "Kanpur Nagar",
    "UP30": "Farrukhabad",
    "UP31": "Kannauj",
    "UP32": "Lucknow",
    "UP33": "Unnao",
    "UP34": "Raebareli",
    "UP35": "Sitapur",
    "UP36": "Lakhimpur Kheri",
    "UP37": "Hardoi",
    "UP38": "Barabanki",
    "UP39": "Faizabad",
    "UP40": "Ambedkar Nagar",
    "UP41": "Sultanpur",
    "UP42": "Amethi",
    "UP43": "Bahraich",
    "UP44": "Shravasti",
    "UP45": "Gonda",
    "UP46": "Balrampur",
    "UP47": "Basti",
    "UP48": "Sant Kabir Nagar",
    "UP49": "Siddharthnagar",
    "UP50": "Gorakhpur",
    "UP51": "Deoria",
    "UP52": "Kushinagar",
    "UP53": "Maharajganj",
    "UP54": "Azamgarh",
    "UP55": "Mau",
    "UP56": "Ballia",
    "UP57": "Jaunpur",
    "UP58": "Ghazipur",
    "UP59": "Chandauli",
    "UP60": "Varanasi",
    "UP61": "Sant Ravidas Nagar (Bhadohi)",
    "UP62": "Mirzapur",
    "UP63": "Sonbhadra",
    "UP64": "Allahabad (Prayagraj)",
    "UP65": "Kaushambi",
    "UP66": "Fatehpur",
    "UP67": "Pratapgarh",
    "UP68": "Jhansi",
    "UP69": "Lalitpur",
    "UP70": "Jalaun",
    "UP71": "Hamirpur",
    "UP72": "Mahoba",
    "UP73": "Banda",
    "UP74": "Chitrakoot",
    //West Bengal
    "WB01": "Kolkata (North)",
    "WB02": "Kolkata (South)",
    "WB03": "Kolkata (West)",
    "WB04": "Kolkata (East)",
    "WB05": "Barrackpore",
    "WB06": "Barasat",
    "WB07": "Howrah",
    "WB08": "Hooghly",
    "WB09": "Burdwan",
    "WB10": "Asansol",
    "WB11": "Durgapur",
    "WB12": "Kharagpur",
    "WB13": "Tamluk",
    "WB14": "Contai",
    "WB15": "Bankura",
    "WB16": "Purulia",
    "WB17": "Midnapore",
    "WB18": "Alipurduar",
    "WB19": "Cooch Behar",
    "WB20": "Jalpaiguri",
    "WB21": "Darjeeling",
    "WB22": "Kalimpong",
    "WB23": "Raiganj",
    "WB24": "Balurghat",
    "WB25": "Malda",
    "WB26": "Berhampore",
    "WB27": "Krishnanagar",
    "WB28": "Nabadwip",
    "WB29": "Baruipur",
    "WB30": "Diamond Harbour",
    "WB31": "Baharampur (Murshidabad)",
    "WB32": "Kolkata (Private vehicles)",
    "WB33": "Kolkata (Commercial vehicles)",
    "WB34": "North 24 Parganas",
    "WB35": "South 24 Parganas",
    "WB36": "Birbhum",
    "WB37": "Rampurhat",
    "WB38": "Bolpur",
    "WB39": "Nadia (Kalyani)",
    "WB40": "Jhargram"
  };
}
