// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHobAmFqSYVpuN9y_HFfvgGwZ_49ygM_0',
    appId: '1:291574915194:web:f26548f344b90e5e965bc3',
    messagingSenderId: '291574915194',
    projectId: 'easy-insurance-calculator',
    authDomain: 'easy-insurance-calculator.firebaseapp.com',
    storageBucket: 'easy-insurance-calculator.firebasestorage.app',
    measurementId: 'G-WDYRJ48QQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwQXB2EJv8GkvbfDs7cvMTRy9cSOvFpiU',
    appId: '1:291574915194:android:fea4ccbcdd9c1fba965bc3',
    messagingSenderId: '291574915194',
    projectId: 'easy-insurance-calculator',
    storageBucket: 'easy-insurance-calculator.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxD9yLQNxW3apSpYLTCJyKd-XSrhtJ4-4',
    appId: '1:291574915194:ios:8ce32e5305be1fc7965bc3',
    messagingSenderId: '291574915194',
    projectId: 'easy-insurance-calculator',
    storageBucket: 'easy-insurance-calculator.firebasestorage.app',
    iosBundleId: 'com.example.motorInsuranceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxD9yLQNxW3apSpYLTCJyKd-XSrhtJ4-4',
    appId: '1:291574915194:ios:8ce32e5305be1fc7965bc3',
    messagingSenderId: '291574915194',
    projectId: 'easy-insurance-calculator',
    storageBucket: 'easy-insurance-calculator.firebasestorage.app',
    iosBundleId: 'com.example.motorInsuranceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHobAmFqSYVpuN9y_HFfvgGwZ_49ygM_0',
    appId: '1:291574915194:web:9c391f23be049aa6965bc3',
    messagingSenderId: '291574915194',
    projectId: 'easy-insurance-calculator',
    authDomain: 'easy-insurance-calculator.firebaseapp.com',
    storageBucket: 'easy-insurance-calculator.firebasestorage.app',
    measurementId: 'G-8MXVETQMLC',
  );
}
